dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - export VERSION=0.0.1
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --build-arg VERSION=$VERSION -t jenkins-build-by-token-action:$VERSION -f Dockerfile .
      - docker images
      - docker tag jenkins-build-by-token-action:$VERSION $DOCKER_USERNAME/jenkins-build-by-token-action:$VERSION
      - docker push $DOCKER_USERNAME/jenkins-build-by-token-action:$VERSION
